services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    tty: true
    command: yarn dev